server {
    listen       80;
    server_name  _;
    root   /usr/share/nginx/html;
    index  index.html;

    # SPA: serve index.html for any non-file route
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Optional: tune client max body size if uploading files
    client_max_body_size 10M;
}
